version: '3.8'
services:

  db:
    image: mysql:5.7
    container_name: db
    environment:
      - DATABASE_HOST=localhost
      - DATABASE_PORT=3306
      - DATABASE_NAME=devops
      - DATABASE_USER=root
      - DATABASE_PASSWORD=
    ports:
      - 3306:3306

  html:
    build: ./html
    container_name: html
    ports:
      - 80:80

  web:
    build: ./web
    container_name: web
    ports:
      - 8080:8080

    depends_on:
      - db
