name: Build and push Docker image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Docker
        uses: docker/setup-docker@v2

      - name: Build image
        run: docker build -t flask-microservice:latest .

      - name: Push image
        run: docker push flask-microservice:latest

      - name: Create database
        run: mysql -h localhost -P 3306 -u root -p < create_database.sql
